all: modularity_good modularity_bad

modularity_good: modularity_good.cpp
	g++ -o modularity_good modularity_good.cpp

modularity_bad: modularity_bad.cpp
	g++ -o modularity_bad modularity_bad.cpp

clean:
rm modularity_good modularity_bad
