all: leastPrivilege_good leastPrivilege_bad

leastPrivilege_good: leastPrivilege_good.cpp
	g++ -o leastPrivilege_good leastPrivilege_good.cpp

leastPrivilege_bad: leastPrivilege_bad.cpp
	g++ -o leastPrivilege_bad leastPrivilege_bad.cpp

clean:
rm leastPrivilege_good leastPrivilege_bad
