all: layering_good layering_bad

layering_good: layering_good.cpp
	g++ -o layering_good layering_good.cpp

layering_bad: layering_bad.cpp
	g++ -o layering_bad layering_bad.cpp

clean:
rm layering_good layering_bad
