all: dataHiding_good dataHiding_bad

dataHiding_good: dataHiding_good.cpp
	g++ -o dataHiding_good dataHiding_good.cpp

dataHiding_bad: dataHiding_bad.cpp
	g++ -o dataHiding_bad dataHiding_bad.cpp

clean:
rm dataHiding_good dataHiding_bad
