all: simplicity_good simplicity_bad

simplicity_good: simplicity_good.cpp simplicity_good.h
	g++ -o simplicity_good simplicity_good.cpp simplicity_good.h

simplicity_bad: simplicity_bad.cpp
	g++ -o simplicity_bad simplicity_bad.cpp

clean:
	rm simplicity_good simplicity_bad
