
all: resourceEncapsulation_good resourceEncapsulation_bad

resourceEncapsulation_good: resourceEncapsulation_good.cpp
	g++ -o resourceEncapsulation_good resourceEncapsulation_good.cpp

resourceEncapsulation_bad: resourceEncapsulation_bad.cpp
	g++ -o resourceEncapsulation_bad resourceEncapsulation_bad.cpp

clean:
rm resourceEncapsulation_good resourceEncapsulation_bad
