all: domainSeparation_good domainSeparation_bad

domainSeparation_good: domainSeparation_good.cpp
	g++ -o domainSeparation_good domainSeparation_good.cpp

domainSeparation_bad: domainSeparation_bad.cpp
	g++ -o domainSeparation_bad domainSeparation_bad.cpp

clean:
	rm domainSeparation_good domainSeparation_bad
